### ISSUE TITLE
Add typos pre-commit

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek-docs#305]
In the main Zeek repository, we have a pre-commit rule that checks for typos in comment strings and such. I'm somewhat surprised that we hadn't already added it to this repo too. It will take some work to get the set of exclusions correct so that it's not fixing things it shouldn't, but a quick test run finds a lot of worthy changes. This is the rule that needs to be added:

```
- repo: https://github.com/crate-ci/typos
  rev: v1.30.1
  hooks:
    - id: typos
```

See https://github.com/zeek/zeek/blob/master/.typos.toml for an example of the exclusions file.
